// This file is generated by Fresh. Do not modify.
import { type Manifest } from "$fresh/server.ts";
import * as $$_APP from "./routes/_app.tsx";
import * as $$_INDEX from "./routes/index.tsx";
import * as $$_LOGIN from "./routes/login.tsx";
import * as $$_REGISTER from "./routes/register.tsx";
import * as $$_LOGOUT from "./routes/logout.ts";
import * as $$_API_EXPENSES from "./routes/api/expenses.ts";
import * as $$_API_AUTH from "./routes/api/auth.ts";
import * as $_EXPENSE_FORM from "./islands/ExpenseForm.tsx";
import * as $_EXPENSE_LIST from "./islands/ExpenseList.tsx";
import * as $_EXPENSE_CHART from "./islands/ExpenseChart.tsx";

const manifest: Manifest = {
  routes: {
    "./routes/_app.tsx": $$_APP,
    "./routes/index.tsx": $$_INDEX,
    "./routes/login.tsx": $$_LOGIN,
    "./routes/register.tsx": $$_REGISTER,
    "./routes/logout.ts": $$_LOGOUT,
    "./routes/api/expenses.ts": $$_API_EXPENSES,
    "./routes/api/auth.ts": $$_API_AUTH,
  },
  islands: {
    "./islands/ExpenseForm.tsx": $_EXPENSE_FORM,
    "./islands/ExpenseList.tsx": $_EXPENSE_LIST,
    "./islands/ExpenseChart.tsx": $_EXPENSE_CHART,
  },
  baseUrl: import.meta.url,
};

export default manifest;
